-- =============================================================================
-- AI-Ready School — CONTENT SEED (for auditing/populating without a terminal)
--
-- HOW TO USE:
--   1) Run supabase/schema.sql first (safe/idempotent — creates the PD tables,
--      policies, and the subject/pillar columns).
--   2) Then run THIS file in Supabase → SQL Editor.
--
-- It REPLACES the sample Cookbook, downloads, and PD courses with the full
-- starter library, so the Owner portal is fully populated to audit.
--
-- NOTE: download FILES (PDFs) are not created here (SQL can't upload files).
-- The download rows will list in the portal; to make the files downloadable,
-- run `npm run seed` (uses the service-role key) or upload via Owner → Resources.
-- =============================================================================

alter table public.recipes   add column if not exists subject text not null default 'Cross-curricular';
alter table public.recipes   add column if not exists pillar text;
alter table public.resources add column if not exists pillar text;

-- Clean slate for the sample library (keeps user accounts/licenses untouched).
delete from public.pd_lessons;
delete from public.pd_courses;
delete from public.resources;
delete from public.recipes;

-- ---------- COOKBOOK PROMPTS -------------------------------------------------
insert into public.recipes (title, subject, category, grade_band, summary, prompt_text, min_role, pillar) values
('Lesson hook generator','Cross-curricular','Planning','All grades','Spin up three attention-grabbing openings for any lesson.','Give me three different 5-minute lesson hooks for a lesson on [TOPIC] for a [GRADE] class. One should be a question, one a quick activity, and one a surprising fact. Keep them practical for a classroom.','teacher','Teacher Productivity'),
('Differentiate this task (3 levels)','Cross-curricular','Differentiation','3-5','Turn one activity into support, on-level, and extension versions.','Take this activity: [PASTE ACTIVITY]. Create three versions — one with more scaffolding, one on grade level, and one extension — for a mixed 3rd-5th grade class. Do not reference any specific student.','teacher','Teacher Productivity'),
('Rubric builder','Cross-curricular','Assessment','6-8','A clear 4-level rubric in student-friendly language.','Create a 4-level rubric for this assignment: [DESCRIBE ASSIGNMENT]. Use these criteria: [LIST 3-4 CRITERIA]. Write the descriptors so a middle schooler can self-assess.','teacher','Teacher Productivity'),
('Parent email (first draft)','Cross-curricular','Communication','All grades','A warm, professional draft you personalize before sending.','Draft a warm, professional email to a parent about [GENERAL TOPIC, e.g. an upcoming project]. Keep it under 150 words. Use the placeholder [Student] instead of any real name — I''ll fill it in myself.','teacher','Teacher Productivity'),
('Exit ticket set','Cross-curricular','Assessment','All grades','Three quick checks for understanding at three levels.','Based on this objective: [PASTE OBJECTIVE], write three exit-ticket questions — one recall, one application, one reflection — each answerable in under two minutes.','teacher','Teacher Productivity'),
('Sub plan in a pinch','Cross-curricular','Administrative','All grades','A ready-to-leave substitute plan for an unexpected absence.','Write a clear one-page substitute plan for a [GRADE] class for a lesson on [TOPIC]. Include a bell-ringer, a main activity with simple directions, an early-finisher task, and classroom management notes. Assume the sub doesn''t know the students.','teacher','Teacher Productivity'),
('Feedback sentence starters','Cross-curricular','Feedback','6-8','Kind, specific, actionable feedback stems you can reuse.','Give me 10 feedback sentence starters for middle school work that are kind, specific, and actionable. Group them by ''glow'' (strength) and ''grow'' (next step). Keep them general so I can apply them to any student''s work.','teacher','Teacher Productivity'),
('Reading passage leveler','English Language Arts','Differentiation','9-12','Rewrite a text to a target reading level, keeping key ideas.','Rewrite the following passage at a [GRADE] reading level while keeping the essential vocabulary I mark: [PASTE PASSAGE]. Then add three comprehension questions.','teacher','AI in the Classroom by Subject'),
('Text-dependent question set','English Language Arts','Assessment','6-8','Layered questions that push students back into the text.','For this passage: [PASTE PASSAGE], write six text-dependent questions that build from literal comprehension to inference to author''s craft. Mark which standard each targets.','teacher','AI in the Classroom by Subject'),
('Mentor-sentence mini-lesson','English Language Arts','Planning','3-5','A short grammar lesson built around one strong sentence.','Build a 10-minute mentor-sentence lesson for [GRADE] using this sentence: [PASTE SENTENCE]. Include what to notice, a guided imitation, and an independent try.','teacher','AI in the Classroom by Subject'),
('Word problems in a real context','Mathematics','Planning','3-5','Fresh word problems tied to a theme students care about.','Write five [GRADE] word problems practicing [SKILL, e.g. multi-digit addition] set in the context of [THEME, e.g. a school fundraiser]. Include an answer key with worked steps.','teacher','AI in the Classroom by Subject'),
('Error-analysis task','Mathematics','Assessment','6-8','A worked problem with a mistake for students to catch.','Create a worked solution to a [TOPIC] problem that contains one common misconception, then ask students to find and fix the error and explain their reasoning. Give me the intended error and the correct work.','teacher','AI in the Classroom by Subject'),
('Three-read math routine','Mathematics','Differentiation','9-12','Scaffold a dense problem with a structured reading routine.','Turn this problem into a ''three-read'' routine (what''s the situation, what''s the question, what information matters): [PASTE PROBLEM]. Provide the prompts I''d ask at each read.','teacher','AI in the Classroom by Subject'),
('Phenomenon-based lesson opener','Science','Planning','6-8','Anchor a unit in a puzzling real-world phenomenon.','Suggest three puzzling, observable phenomena that could anchor a [GRADE] unit on [TOPIC]. For each, give a driving question students could investigate.','teacher','AI in the Classroom by Subject'),
('Lab safety + procedure rewrite','Science','Differentiation','9-12','Simplify a lab procedure and surface the safety steps.','Rewrite this lab procedure at a [GRADE] reading level with numbered steps, and add a short safety checklist at the top: [PASTE PROCEDURE].','teacher','AI in the Classroom by Subject'),
('Primary-source discussion guide','Social Studies','Planning','9-12','Turn a document into a sourcing-and-discussion activity.','For this primary source: [PASTE SOURCE], create a discussion guide with sourcing questions (who, when, why), two points of view to compare, and a closing prompt.','teacher','AI in the Classroom by Subject'),
('Debate prep, both sides','Social Studies','Planning','6-8','Balanced talking points so every student can participate.','Give balanced, grade-appropriate talking points for both sides of this question for a [GRADE] class: [QUESTION]. Add three sentence stems for respectful disagreement.','teacher','AI in the Classroom by Subject'),
('Comprehensible-input story','World Languages','Planning','9-12','A short leveled story recycling target vocabulary.','Write a short story in [LANGUAGE] at a novice-mid level that repeats these target words: [LIST WORDS]. Keep sentences simple and add a 5-question comprehension check.','teacher','AI in the Classroom by Subject'),
('Choice-board of creative tasks','The Arts','Differentiation','3-5','A menu of ways to show learning through art.','Design a 3x3 choice board where students demonstrate understanding of [TOPIC] through visual, performing, and design tasks. Keep materials low-cost and directions short.','teacher','AI in the Classroom by Subject'),
('Station rotation with modifications','PE & Health','Planning','K-2','Active stations with easier/harder options built in.','Plan four movement stations for a [GRADE] class practicing [SKILL]. For each, give an easier and a harder modification and a simple safety cue.','teacher','AI in the Classroom by Subject'),
('Shop project spec sheet','Career & Technical Education','Planning','9-12','A clear build spec with steps, tools, and checkpoints.','Write a project spec for a [PROJECT, e.g. small storage box] in a high school woodshop: materials list, cut list, ordered build steps, tools per step, and three quality checkpoints. Add a safety reminder for each power tool used.','teacher','AI in the Classroom by Subject'),
('Industry-standard rubric','Career & Technical Education','Assessment','9-12','Grade craftsmanship the way the trade would.','Create a 4-level rubric for a [PROJECT] that assesses craftsmanship, accuracy to spec, safe tool use, and shop cleanup — using language a tradesperson would recognize.','teacher','AI in the Classroom by Subject'),
('Circle-time plan with a book','Early Childhood','Planning','K-2','A developmentally-appropriate circle time around one theme.','Plan a 15-minute circle time for preschoolers on [THEME]. Include a greeting song, a read-aloud with two talking points, a movement break, and a simple closing routine. Keep language concrete and warm.','teacher','Early Childhood AI'),
('Play-based center ideas','Early Childhood','Differentiation','K-2','Learning centers that build one skill through play.','Suggest four play-based learning centers for preschoolers practicing [SKILL, e.g. letter sounds]. For each, list the materials and one open-ended question a teacher could ask.','teacher','Early Childhood AI'),
('UDL options for one lesson','Accessibility & Equity','Differentiation','All grades','Multiple means of engagement, representation, and expression.','Using Universal Design for Learning, suggest options for this lesson: [PASTE LESSON]. Give me choices for how students engage, how content is represented, and how they can show what they know. Keep suggestions general, not about any specific student.','teacher','AI for Accessibility & Equity'),
('Scaffold for multilingual learners','Accessibility & Equity','Differentiation','6-8','Language supports that keep the content rigorous.','Add language scaffolds to this task for multilingual learners at an intermediate proficiency: [PASTE TASK]. Include a word bank, two sentence frames, and a visual suggestion — without lowering the thinking demand.','teacher','AI for Accessibility & Equity'),
('Turn my notes into a lesson plan','Teacher Productivity','Planning','All grades','Messy notes in, a clean structured plan out.','Turn these rough notes into a structured [GRADE] lesson plan with objective, materials, timed sequence, and a check for understanding: [PASTE NOTES].','teacher','Teacher Productivity'),
('Newsletter blurb from bullet points','Teacher Productivity','Communication','All grades','A friendly class-newsletter paragraph in seconds.','Write a warm 120-word class newsletter blurb from these bullet points: [PASTE BULLETS]. Keep it parent-friendly and use [Student]/[the class] instead of real names.','teacher','Teacher Productivity');

-- ---------- DOWNLOADS (metadata; run npm run seed to attach the PDF files) ---
insert into public.resources (title, description, category, type, file_path, min_role, pillar) values
('Teacher Quick-Start Handout','One page: the golden rules of safe AI use + how to use the Cookbook.','Teacher Resources','file','seed/teacher-quickstart.pdf','teacher','AI Safety & Policy'),
('AI Acceptable-Use Policy (template)','Board-ready starter policy for staff and student AI use.','Governance','file','seed/ai-acceptable-use-policy.pdf','school_admin','AI Safety & Policy'),
('FERPA-Safe One-Pager','Plain-language guidance on student privacy and AI.','Governance','file','seed/ferpa-safe-one-pager.pdf','school_admin','AI Safety & Policy'),
('Family Letter (template)','A ready-to-send letter explaining your AI approach to families.','Communication','file','seed/family-letter.pdf','school_admin','AI Safety & Policy'),
('Staff AI Agreement (template)','A short acknowledgment staff sign before using AI tools.','Governance','file','seed/staff-ai-agreement.pdf','school_admin','AI Safety & Policy'),
('Facilitator PD Deck (outline)','A 45-minute staff PD outline with talking points and timings.','Training','file','seed/facilitator-pd-outline.pdf','school_admin','AI Safety & Policy'),
('Rollout Playbook','A step-by-step plan to go live across a building in about a week.','Governance','file','seed/rollout-playbook.pdf','school_admin','AI Safety & Policy');

-- ---------- PD COURSES -------------------------------------------------------
insert into public.pd_courses (pillar, title, summary, audience, est_minutes, min_role, sort_order) values
('AI Safety & Policy','AI Safety & Policy Foundations','The buy-in course: what AI is, the one hard rule, a pre-flight safety check, and your policy in plain language.','All staff',30,'teacher',1),
('AI in the Classroom by Subject','Finding & Using the Right AI Tools for Your Subject','How to choose, vet, and use AI tools for your content area — with quick wins by department.','Teachers',35,'teacher',1),
('Early Childhood AI','AI in the Early Childhood Classroom','Developmentally-appropriate AI for the youngest classrooms — teacher-facing wins that keep learning human.','Early Childhood',25,'teacher',1),
('AI for Accessibility & Equity','AI for Accessibility & Equity','Use AI to widen access: UDL, multilingual learners, and privacy-safe IEP/504 supports.','Teachers',30,'teacher',1),
('Student AI Literacy','Teaching Students to Harness AI (Responsibly)','Help students understand the power of AI and how to use it responsibly and age-appropriately.','Teachers',35,'teacher',1),
('Teacher Productivity','Reclaim Your Week with AI','Hand the repetitive work to AI — keep the relational work for you. Build reusable prompts that save hours.','Teachers',25,'teacher',1);

-- ---------- PD LESSONS -------------------------------------------------------
-- Safety & Policy
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='AI Safety & Policy Foundations'),'Why AI, why now','Your students are already using AI, and so are many of your colleagues. The goal of this course is not hype — it is to help you save time on the repetitive parts of teaching and to keep students safe while doing it. By the end you will know the one rule that matters most, a quick check you can run before any AI use, and how your school''s policy protects everyone. Nothing here asks you to change what makes you a great teacher; it just removes risk and gives you hours back.',1),
((select id from public.pd_courses where title='AI Safety & Policy Foundations'),'The one hard rule','Never put student personal information into a public AI tool. Names, grades tied to a name, IEP/504 details, behavior notes, health information, addresses — none of it belongs in a general chatbot, because you cannot control where that data goes next. The good news: you almost never need to. Use placeholders like [Student] or "a 4th-grade student," let the AI do the generic heavy lifting, and fill in the specifics yourself, offline. Treat a public AI tool like a substitute you have never met: helpful, but not someone you hand a student''s file to.',2),
((select id from public.pd_courses where title='AI Safety & Policy Foundations'),'The 10-minute pre-flight check','Before any AI activity, ask three questions. One: does this put any student information into a public tool? If yes, stop and use placeholders. Two: would I be comfortable if a parent saw exactly what I typed in? If not, rework it. Three: am I reviewing the output before it reaches students, instead of using it blindly? If yes to that, you are in good shape. This habit takes minutes and prevents almost every common mistake.',3),
((select id from public.pd_courses where title='AI Safety & Policy Foundations'),'Your AI policy in plain language','A real AI policy is not a 40-page binder. It is a handful of decisions written down: what tools are approved, the privacy rule above, expectations for student use, and who to ask when unsure. This course pairs with downloadable templates — an Acceptable-Use Policy, a FERPA one-pager, a family letter, and a staff agreement — that your leadership can adapt and adopt in a week. Consistency is the point: five teachers should give the same answer about what is allowed.',4);

-- Finding & Using AI Tools by Subject (requested)
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='Finding & Using the Right AI Tools for Your Subject'),'How to choose an AI tool for your content area','Start from the task, not the tool. Name the specific thing you want help with — drafting, leveling a text, generating practice problems, giving feedback — then pick the simplest tool that does it well. Favor tools your district has approved. Ask: does it keep my data private, is it easy enough that I will actually use it weekly, and does it clearly help students learn rather than just do the work for them? A tool that saves you ten minutes on a Tuesday beats a flashy one you never open.',1),
((select id from public.pd_courses where title='Finding & Using the Right AI Tools for Your Subject'),'A quick tour of tool types','Most classroom AI falls into a few buckets: chat assistants (drafting, explaining, brainstorming), document helpers (summarizing, leveling, formatting), image and design tools (visuals, slides), and subject-specific tools (math practice, reading support, world-language conversation). You do not need all of them. Learn one chat assistant well first — it covers 80% of what teachers need — then add a subject-specific tool only where it clearly earns its place.',2),
((select id from public.pd_courses where title='Finding & Using the Right AI Tools for Your Subject'),'Subject playbooks: quick wins by department','ELA: level a passage and generate text-dependent questions. Math: create error-analysis tasks and contextual word problems. Science: brainstorm anchoring phenomena and simplify lab procedures. Social studies: build sourcing questions and balanced debate prep. World languages: generate comprehensible-input stories. CTE/electives: draft project specs and industry-style rubrics. Every one of these has a matching prompt in your Cookbook — start there, then adapt.',3),
((select id from public.pd_courses where title='Finding & Using the Right AI Tools for Your Subject'),'Vetting a tool for privacy before you use it','Before adopting anything new, do a two-minute check: Is it on the district-approved list? Does it require student logins or collect student data — and if so, is there a signed agreement? Can you use it teacher-side only, with placeholders, to avoid student data entirely? When in doubt, keep it teacher-facing and bring the tool to your administrator before putting it in front of students.',4);

-- Early Childhood
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='AI in the Early Childhood Classroom'),'What''s developmentally appropriate (and what isn''t)','In early childhood, the youngest learners should not be interacting with AI tools directly — their learning is hands-on, social, and play-based. Where AI helps is teacher-side: planning, differentiating, and communicating. Think of AI as a prep assistant that gives you more time on the carpet, not a screen for the children. Keep the classroom experience about people, materials, and play.',1),
((select id from public.pd_courses where title='AI in the Early Childhood Classroom'),'Teacher-facing wins','Use AI to draft circle-time plans around a theme, generate play-based center ideas for a target skill, write warm family notes and newsletters, and rephrase a tricky message to a parent. Always keep children''s names and details out of the tool — describe needs generally and personalize afterward. The matching Cookbook prompts (circle-time plan, play-based centers) are a fast start.',2),
((select id from public.pd_courses where title='AI in the Early Childhood Classroom'),'Keeping it human','Routines, relationships, and play are the curriculum at this age, and none of that is outsourced. Let AI clear your prep pile so you have more energy for the read-aloud, the sensory bin, and the child who needs an extra minute at drop-off. Used this way, AI protects the human core of early-childhood teaching instead of competing with it.',3);

-- Accessibility & Equity
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='AI for Accessibility & Equity'),'UDL with AI: multiple means, one lesson','Universal Design for Learning asks us to offer multiple means of engagement, representation, and expression. AI makes that fast: from one lesson, generate a choice of entry points, a leveled version of the text, a visual explanation, and two or three ways students can show what they know. Ask for options, keep them general (not about any named student), and choose what fits your class.',1),
((select id from public.pd_courses where title='AI for Accessibility & Equity'),'Supporting multilingual learners','AI can add scaffolds without lowering the thinking demand: a word bank, sentence frames, a simplified-language version alongside the original, and a visual suggestion. Describe the proficiency level generally and never paste identifying student information. The goal is access to the same rigorous content, not a watered-down task.',2),
((select id from public.pd_courses where title='AI for Accessibility & Equity'),'IEP/504 supports — privacy-safe','You can use AI to brainstorm accommodations and rephrase goals in plain language — but never paste a student''s actual IEP, name, or disability details into a public tool. Describe the need in general terms ("a student who benefits from chunked directions and extra processing time") and apply the ideas yourself. Keep all record-level work inside district-approved systems.',3);

-- Student AI Literacy (requested)
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='Teaching Students to Harness AI (Responsibly)'),'The power of AI — what students should understand','Students should know both what AI can do and what it cannot. It is a powerful thinking partner — it can explain, draft, brainstorm, and give feedback — but it can also be confidently wrong, biased, and unaware of them as people. Framing matters: AI is a tool they direct, not an authority they defer to. The skill we are teaching is judgment: how to get value from AI while staying the thinker in charge.',1),
((select id from public.pd_courses where title='Teaching Students to Harness AI (Responsibly)'),'Responsible, age-appropriate use by grade band','Expectations scale with age. Younger students focus on honesty ("did you do the thinking?") and never sharing personal information. Middle grades add fact-checking and citing when AI helped. High schoolers tackle deeper questions: bias, verification, and using AI to strengthen — not replace — their own work. Match the conversation to the grade in front of you.',2),
((select id from public.pd_courses where title='Teaching Students to Harness AI (Responsibly)'),'Academic integrity in an AI world','Blanket bans rarely work; clear expectations do. Decide per assignment where AI is allowed (brainstorming? drafting? not at all?) and say so in writing. Teach students to disclose how they used AI, the way they would cite a source. Design some assessments that center process — drafts, reflections, in-class work — so the thinking is visible.',3),
((select id from public.pd_courses where title='Teaching Students to Harness AI (Responsibly)'),'A classroom AI agreement students help write','Students follow rules they help make. Co-create a short classroom AI agreement: when AI is okay, when it is not, how to be honest about using it, and the privacy rule (never share personal information). Keep it to a handful of lines, post it, and revisit it. Ownership turns "rules" into a shared standard.',4);

-- Teacher Productivity
insert into public.pd_lessons (course_id, title, body, sort_order) values
((select id from public.pd_courses where title='Reclaim Your Week with AI'),'Where AI belongs: the repetitive, not the relational','The best use of AI is on tasks that do not require knowing your students: first drafts, reformatting, summarizing, and boilerplate communication. The relational, judgment-heavy work — reading the room, responding to a struggling student, building trust — stays with you. If a task requires knowing your kids, you do it; if it does not, let AI take the first pass.',1),
((select id from public.pd_courses where title='Reclaim Your Week with AI'),'Five tasks to hand off this week','Try these: draft a parent email from a few bullet points, turn messy notes into a lesson plan, generate three exit-ticket questions from your objective, write a class-newsletter blurb, and build a quick rubric. Each has a Cookbook prompt. Reviewing and editing an AI draft is far faster than starting from a blank page.',2),
((select id from public.pd_courses where title='Reclaim Your Week with AI'),'Build your own reusable prompts','When a prompt works, save it. Keep a personal note of your best prompts with [PLACEHOLDERS] where the specifics go, so next time you paste and swap instead of rewriting. Over a semester, a small library of your own reliable prompts is where the real time savings compound.',3);
